<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4a4b4cb3-1304-4e95-9ccd-acd92437d03b</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <OpenApiDocumentsDirectory>.</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
  </PropertyGroup>

  <PropertyGroup>
      <!-- If you pass -p:SWAGGER=true, also add SWAGGER to DefineConstants -->
      <DefineConstants Condition="'$(SWAGGER)'=='true'">$(DefineConstants);SWAGGER</DefineConstants>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
	  <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="9.0.10">
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	    <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="9.0.11" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.14.1" />
    <PackageReference Include="MockQueryable.Moq" Version="8.0.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.15.0.120848">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp.Styling" Version="10.15.0.120848">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" Condition="'$(SWAGGER)' != ''" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend.DependencyInjection\UCR.ECCI.PI.ThemePark.Backend.DependencyInjection.csproj" />
    <ProjectReference Include="..\Backend.Presentation.Api\UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.csproj" />
  </ItemGroup>

    <PropertyGroup>
        <SonarQubeTestProject>false</SonarQubeTestProject>
    </PropertyGroup>
</Project>
