// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models;
namespace UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Laboratories.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \laboratories\{laboratoryId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLaboratoryItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Laboratories.Item.WithLaboratoryItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLaboratoryItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/laboratories/{laboratoryId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Laboratories.Item.WithLaboratoryItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLaboratoryItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/laboratories/{laboratoryId}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.DeleteLearningSpaceResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceNotFoundErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceConflictErrorResponse">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.DeleteLearningSpaceResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.DeleteLearningSpaceResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceNotFoundErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceConflictErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.DeleteLearningSpaceResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.DeleteLearningSpaceResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.GetLaboratoryResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceNotFoundErrorResponse">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.GetLaboratoryResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.GetLaboratoryResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceNotFoundErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.GetLaboratoryResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.GetLaboratoryResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceValidationErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceNotFoundErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceConflictErrorResponse">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryResponse?> PutAsync(global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryResponse> PutAsync(global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceValidationErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceNotFoundErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceConflictErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.UpdateLaboratoryRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Laboratories.Item.WithLaboratoryItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Laboratories.Item.WithLaboratoryItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Laboratories.Item.WithLaboratoryItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithLaboratoryItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithLaboratoryItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithLaboratoryItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
