// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Item;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Paged;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms
{
    /// <summary>
    /// Builds and executes requests for operations under \classrooms
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClassroomsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The paged property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Paged.PagedRequestBuilder Paged
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Paged.PagedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.classrooms.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Item.WithClassroomItemRequestBuilder"/></returns>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Item.WithClassroomItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("classroomId", position);
                return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Item.WithClassroomItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.classrooms.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Item.WithClassroomItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Item.WithClassroomItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("classroomId", position);
                return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.Item.WithClassroomItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.ClassroomsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClassroomsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/classrooms", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.ClassroomsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClassroomsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/classrooms", rawUrl)
        {
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.ListClassroomsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.ListClassroomsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.ListClassroomsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.ListClassroomsResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.ListClassroomsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.LearningSpaceValidationErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.LearningSpaceConflictErrorResponse">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomResponse?> PostAsync(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomResponse> PostAsync(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.LearningSpaceValidationErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.LearningSpaceConflictErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.ClassroomsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.ClassroomsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.ClassroomsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClassroomsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClassroomsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
