<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="ModelContextProtocol" Version="0.3.0-preview.4" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.3.0-preview.4" />
    <PackageReference Include="System.Threading.Channels" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend.Presentation.Api\UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

    <PropertyGroup>
        <SonarQubeTestProject>false</SonarQubeTestProject>
    </PropertyGroup>
</Project>
