// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BoardDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The depth property</summary>
        public double? Depth { get; set; }
        /// <summary>The height property</summary>
        public double? Height { get; set; }
        /// <summary>The learningSpaceId property</summary>
        public int? LearningSpaceId { get; set; }
        /// <summary>The markerColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MarkerColor { get; set; }
#nullable restore
#else
        public string MarkerColor { get; set; }
#endif
        /// <summary>The plateId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlateId { get; set; }
#nullable restore
#else
        public string PlateId { get; set; }
#endif
        /// <summary>The texture property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Texture { get; set; }
#nullable restore
#else
        public string Texture { get; set; }
#endif
        /// <summary>The width property</summary>
        public double? Width { get; set; }
        /// <summary>The x property</summary>
        public double? X { get; set; }
        /// <summary>The xAxisRotation property</summary>
        public double? XAxisRotation { get; set; }
        /// <summary>The y property</summary>
        public double? Y { get; set; }
        /// <summary>The yAxisRotation property</summary>
        public double? YAxisRotation { get; set; }
        /// <summary>The z property</summary>
        public double? Z { get; set; }
        /// <summary>The zAxisRotation property</summary>
        public double? ZAxisRotation { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BoardDto"/> and sets the default values.
        /// </summary>
        public BoardDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BoardDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BoardDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BoardDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "color", n => { Color = n.GetStringValue(); } },
                { "depth", n => { Depth = n.GetDoubleValue(); } },
                { "height", n => { Height = n.GetDoubleValue(); } },
                { "learningSpaceId", n => { LearningSpaceId = n.GetIntValue(); } },
                { "markerColor", n => { MarkerColor = n.GetStringValue(); } },
                { "plateId", n => { PlateId = n.GetStringValue(); } },
                { "texture", n => { Texture = n.GetStringValue(); } },
                { "width", n => { Width = n.GetDoubleValue(); } },
                { "x", n => { X = n.GetDoubleValue(); } },
                { "xAxisRotation", n => { XAxisRotation = n.GetDoubleValue(); } },
                { "y", n => { Y = n.GetDoubleValue(); } },
                { "yAxisRotation", n => { YAxisRotation = n.GetDoubleValue(); } },
                { "z", n => { Z = n.GetDoubleValue(); } },
                { "zAxisRotation", n => { ZAxisRotation = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("color", Color);
            writer.WriteDoubleValue("depth", Depth);
            writer.WriteDoubleValue("height", Height);
            writer.WriteIntValue("learningSpaceId", LearningSpaceId);
            writer.WriteStringValue("markerColor", MarkerColor);
            writer.WriteStringValue("plateId", PlateId);
            writer.WriteStringValue("texture", Texture);
            writer.WriteDoubleValue("width", Width);
            writer.WriteDoubleValue("x", X);
            writer.WriteDoubleValue("xAxisRotation", XAxisRotation);
            writer.WriteDoubleValue("y", Y);
            writer.WriteDoubleValue("yAxisRotation", YAxisRotation);
            writer.WriteDoubleValue("z", Z);
            writer.WriteDoubleValue("zAxisRotation", ZAxisRotation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
