// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BuildingDtoWithId : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The buildingRenderInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingRenderInfoDto? BuildingRenderInfo { get; set; }
#nullable restore
#else
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingRenderInfoDto BuildingRenderInfo { get; set; }
#endif
        /// <summary>The floorCount property</summary>
        public int? FloorCount { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The officialId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OfficialId { get; set; }
#nullable restore
#else
        public string OfficialId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingDtoWithId"/> and sets the default values.
        /// </summary>
        public BuildingDtoWithId()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingDtoWithId"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingDtoWithId CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingDtoWithId();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buildingRenderInfo", n => { BuildingRenderInfo = n.GetObjectValue<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingRenderInfoDto>(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingRenderInfoDto.CreateFromDiscriminatorValue); } },
                { "floorCount", n => { FloorCount = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "officialId", n => { OfficialId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.BuildingRenderInfoDto>("buildingRenderInfo", BuildingRenderInfo);
            writer.WriteIntValue("floorCount", FloorCount);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("officialId", OfficialId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
