// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateClassroomRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The buildingId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildingId { get; set; }
#nullable restore
#else
        public string BuildingId { get; set; }
#endif
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The floorLevel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FloorLevel { get; set; }
#nullable restore
#else
        public string FloorLevel { get; set; }
#endif
        /// <summary>The height property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Height { get; set; }
#nullable restore
#else
        public string Height { get; set; }
#endif
        /// <summary>The length property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Length { get; set; }
#nullable restore
#else
        public string Length { get; set; }
#endif
        /// <summary>The roomId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoomId { get; set; }
#nullable restore
#else
        public string RoomId { get; set; }
#endif
        /// <summary>The texture property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Texture { get; set; }
#nullable restore
#else
        public string Texture { get; set; }
#endif
        /// <summary>The width property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Width { get; set; }
#nullable restore
#else
        public string Width { get; set; }
#endif
        /// <summary>The xCoordinate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XCoordinate { get; set; }
#nullable restore
#else
        public string XCoordinate { get; set; }
#endif
        /// <summary>The yCoordinate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YCoordinate { get; set; }
#nullable restore
#else
        public string YCoordinate { get; set; }
#endif
        /// <summary>The zCoordinate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZCoordinate { get; set; }
#nullable restore
#else
        public string ZCoordinate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest"/> and sets the default values.
        /// </summary>
        public CreateClassroomRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateClassroomRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buildingId", n => { BuildingId = n.GetStringValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "floorLevel", n => { FloorLevel = n.GetStringValue(); } },
                { "height", n => { Height = n.GetStringValue(); } },
                { "length", n => { Length = n.GetStringValue(); } },
                { "roomId", n => { RoomId = n.GetStringValue(); } },
                { "texture", n => { Texture = n.GetStringValue(); } },
                { "width", n => { Width = n.GetStringValue(); } },
                { "xCoordinate", n => { XCoordinate = n.GetStringValue(); } },
                { "yCoordinate", n => { YCoordinate = n.GetStringValue(); } },
                { "zCoordinate", n => { ZCoordinate = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("buildingId", BuildingId);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("floorLevel", FloorLevel);
            writer.WriteStringValue("height", Height);
            writer.WriteStringValue("length", Length);
            writer.WriteStringValue("roomId", RoomId);
            writer.WriteStringValue("texture", Texture);
            writer.WriteStringValue("width", Width);
            writer.WriteStringValue("xCoordinate", XCoordinate);
            writer.WriteStringValue("yCoordinate", YCoordinate);
            writer.WriteStringValue("zCoordinate", ZCoordinate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
