// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.AsignRoleToUser;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.AssignPermissionToRole;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Buildings;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Laboratories;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Learningspaces;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Permissions;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Register;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Roles;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.SearchRoles;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.SearchUsers;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The asignRoleToUser property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.AsignRoleToUser.AsignRoleToUserRequestBuilder AsignRoleToUser
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.AsignRoleToUser.AsignRoleToUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignPermissionToRole property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.AssignPermissionToRole.AssignPermissionToRoleRequestBuilder AssignPermissionToRole
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.AssignPermissionToRole.AssignPermissionToRoleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The buildings property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Buildings.BuildingsRequestBuilder Buildings
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Buildings.BuildingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The classrooms property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.ClassroomsRequestBuilder Classrooms
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Classrooms.ClassroomsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The interactiveComponents property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.InteractiveComponentsRequestBuilder InteractiveComponents
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.InteractiveComponentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The laboratories property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Laboratories.LaboratoriesRequestBuilder Laboratories
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Laboratories.LaboratoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The learningspaces property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Learningspaces.LearningspacesRequestBuilder Learningspaces
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Learningspaces.LearningspacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Register.RegisterRequestBuilder Register
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Roles.RolesRequestBuilder Roles
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchRoles property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.SearchRoles.SearchRolesRequestBuilder SearchRoles
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.SearchRoles.SearchRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchUsers property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.SearchUsers.SearchUsersRequestBuilder SearchUsers
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.SearchUsers.SearchUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.UsersRequestBuilder Users
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
