// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.Item;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid
{
    /// <summary>
    /// Builds and executes requests for operations under \users\oid
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OidRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.users.oid.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.Item.WithAzureObjectIdentifierItemRequestBuilder"/></returns>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.Item.WithAzureObjectIdentifierItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("azureObjectIdentifier", position);
                return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.Item.WithAzureObjectIdentifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.OidRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OidRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/oid", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.OidRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OidRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/oid", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
