// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Avatar;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Item;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Paginated;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The avatar property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Avatar.AvatarRequestBuilder Avatar
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Avatar.AvatarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oid property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.OidRequestBuilder Oid
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Oid.OidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paginated property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder Paginated
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.users.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Item.AzureObjectIdentifierItemRequestBuilder"/></returns>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Item.AzureObjectIdentifierItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("azureObjectIdentifier%2Did", position);
                return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.Item.AzureObjectIdentifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", rawUrl)
        {
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.GetActiveUsersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.GetActiveUsersResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.GetActiveUsersResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.GetActiveUsersResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.GetActiveUsersResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.ExceptionResult">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse?> PostAsync(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.UserDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse> PostAsync(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.UserDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse.CreateFromDiscriminatorValue },
                { "409", global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse.CreateFromDiscriminatorValue },
                { "500", global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.ExceptionResult.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.CreateUserResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.UserDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Models.UserDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.UsersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.UsersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.Users.UsersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsersRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsersRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
