// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LearningSpaceDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The buildingId property</summary>
        public int? BuildingId { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The floorLevel property</summary>
        public int? FloorLevel { get; set; }
        /// <summary>The height property</summary>
        public float? Height { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The length property</summary>
        public float? Length { get; set; }
        /// <summary>The roomId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoomId { get; set; }
#nullable restore
#else
        public string RoomId { get; set; }
#endif
        /// <summary>The texture property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Texture { get; set; }
#nullable restore
#else
        public string Texture { get; set; }
#endif
        /// <summary>The width property</summary>
        public float? Width { get; set; }
        /// <summary>The xCoordinate property</summary>
        public float? XCoordinate { get; set; }
        /// <summary>The yCoordinate property</summary>
        public float? YCoordinate { get; set; }
        /// <summary>The zCoordinate property</summary>
        public float? ZCoordinate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceDto"/> and sets the default values.
        /// </summary>
        public LearningSpaceDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.LearningSpaceDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buildingId", n => { BuildingId = n.GetIntValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "floorLevel", n => { FloorLevel = n.GetIntValue(); } },
                { "height", n => { Height = n.GetFloatValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "length", n => { Length = n.GetFloatValue(); } },
                { "roomId", n => { RoomId = n.GetStringValue(); } },
                { "texture", n => { Texture = n.GetStringValue(); } },
                { "width", n => { Width = n.GetFloatValue(); } },
                { "xCoordinate", n => { XCoordinate = n.GetFloatValue(); } },
                { "yCoordinate", n => { YCoordinate = n.GetFloatValue(); } },
                { "zCoordinate", n => { ZCoordinate = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("buildingId", BuildingId);
            writer.WriteStringValue("color", Color);
            writer.WriteIntValue("floorLevel", FloorLevel);
            writer.WriteFloatValue("height", Height);
            writer.WriteIntValue("id", Id);
            writer.WriteFloatValue("length", Length);
            writer.WriteStringValue("roomId", RoomId);
            writer.WriteStringValue("texture", Texture);
            writer.WriteFloatValue("width", Width);
            writer.WriteFloatValue("xCoordinate", XCoordinate);
            writer.WriteFloatValue("yCoordinate", YCoordinate);
            writer.WriteFloatValue("zCoordinate", ZCoordinate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
