// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Board;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Boards;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projector;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents
{
    /// <summary>
    /// Builds and executes requests for operations under \interactive-components
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InteractiveComponentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The board property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Board.BoardRequestBuilder Board
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Board.BoardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The boards property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Boards.BoardsRequestBuilder Boards
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Boards.BoardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projector property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projector.ProjectorRequestBuilder Projector
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projector.ProjectorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projectors property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors.ProjectorsRequestBuilder Projectors
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors.ProjectorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.InteractiveComponentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InteractiveComponentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interactive-components", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.InteractiveComponentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InteractiveComponentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interactive-components", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
