// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors.Filter;
namespace UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors
{
    /// <summary>
    /// Builds and executes requests for operations under \interactive-components\projectors
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectorsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filter property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors.Filter.FilterRequestBuilder Filter
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors.Filter.FilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors.ProjectorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectorsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interactive-components/projectors", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Infrastructure.Kiota.InteractiveComponents.Projectors.ProjectorsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectorsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interactive-components/projectors", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
