// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Roles.Item.Permissions;
namespace UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Roles.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \roles\{roleId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRoleItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The permissions property</summary>
        public global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Roles.Item.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Roles.Item.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Roles.Item.WithRoleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoleItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles/{roleId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Roles.Item.WithRoleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoleItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles/{roleId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
