CREATE TABLE [Users].[Role]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(30) NOT NULL,
	CONSTRAINT CK_RoleName_Bound CHECK (LEN(Name) BETWEEN 3 AND 30),
	CONSTRAINT [UQ_Users_Role_Name] UNIQUE ([Name])
)