// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models;
namespace UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated
{
    /// <summary>
    /// Builds and executes requests for operations under \users\paginated
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaginatedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaginatedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/paginated?pageNumber={pageNumber}&pageSize={pageSize}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaginatedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/paginated?pageNumber={pageNumber}&pageSize={pageSize}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.ListActiveusersPagedResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.ListActiveusersPagedResponse?> GetAsync(Action<RequestConfiguration<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder.PaginatedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.ListActiveusersPagedResponse> GetAsync(Action<RequestConfiguration<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder.PaginatedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.ListActiveusersPagedResponse>(requestInfo, global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Models.ListActiveusersPagedResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder.PaginatedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder.PaginatedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class PaginatedRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("pageNumber")]
            public int? PageNumber { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PaginatedRequestBuilderGetRequestConfiguration : RequestConfiguration<global::UCR.ECCI.PI.ThemePark.Unity.Infrastructure.Kiota.Users.Paginated.PaginatedRequestBuilder.PaginatedRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
